# Generated by Django 6.0.3 on 2026-04-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название сообщества"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("school", "Школа"),
                            ("family", "Семья/Район"),
                            ("company", "Компания"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
                ),
            ],
            options={
                "verbose_name": "Сообщество",
                "verbose_name_plural": "Сообщества",
            },
        ),
        migrations.CreateModel(
            name="PointOfDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название точки"),
                ),
                ("address", models.CharField(max_length=500, verbose_name="Адрес")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("library", "Библиотека"),
                            ("office", "Офис"),
                            ("cafe", "Кафе"),
                            ("school", "Школа"),
                        ],
                        max_length=20,
                        verbose_name="Тип точки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="core.community",
                        verbose_name="Сообщество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка выдачи",
                "verbose_name_plural": "Точки выдачи",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("author", models.CharField(max_length=255, verbose_name="Автор")),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("textbook", "Учебник"),
                            ("fiction", "Художественная"),
                            ("professional", "Профессиональная"),
                        ],
                        max_length=20,
                        verbose_name="Тип книги",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Отличное"),
                            ("good", "Хорошее"),
                            ("used", "Поношенное"),
                        ],
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Доступна"),
                            ("reserved", "Забронирована"),
                            ("transferred", "Передана"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="book_covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="core.community",
                        verbose_name="Сообщество",
                    ),
                ),
                (
                    "point_of_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="core.pointofdelivery",
                        verbose_name="Точка выдачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
